// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABRefk-wnMLg02a_eNA__ths7YvZ7a51s',
    appId: '1:464388012261:web:c66021ab56583b4e7a3c0c',
    messagingSenderId: '464388012261',
    projectId: 'gluten-b0992',
    authDomain: 'gluten-b0992.firebaseapp.com',
    storageBucket: 'gluten-b0992.appspot.com',
    measurementId: 'G-TD1Y48KD1J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB762gwFWlWeALC3mrhJdiH6jvkAh6-V48',
    appId: '1:464388012261:android:db1cfab687ecee5e7a3c0c',
    messagingSenderId: '464388012261',
    projectId: 'gluten-b0992',
    storageBucket: 'gluten-b0992.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIkLvvyNssKMno1BB1V2HsqDC8NCsQPu4',
    appId: '1:464388012261:ios:adeab853f834fd407a3c0c',
    messagingSenderId: '464388012261',
    projectId: 'gluten-b0992',
    storageBucket: 'gluten-b0992.appspot.com',
    iosBundleId: 'com.example.gluten',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIkLvvyNssKMno1BB1V2HsqDC8NCsQPu4',
    appId: '1:464388012261:ios:9cc1cc09b4a0cf267a3c0c',
    messagingSenderId: '464388012261',
    projectId: 'gluten-b0992',
    storageBucket: 'gluten-b0992.appspot.com',
    iosBundleId: 'com.example.gluten.RunnerTests',
  );
}
