// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0RxwdIZrUM8hovOI6yM8QryqBG8NkZeg',
    appId: '1:267453690033:web:692859e3102838ddc7b290',
    messagingSenderId: '267453690033',
    projectId: 'gluten-c185f',
    authDomain: 'gluten-c185f.firebaseapp.com',
    storageBucket: 'gluten-c185f.appspot.com',
    measurementId: 'G-8X1L2YE8R8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6uX93JKMLlwmvXZ1deLM8PFaeuCZE8uU',
    appId: '1:267453690033:android:5e573db6d377bce7c7b290',
    messagingSenderId: '267453690033',
    projectId: 'gluten-c185f',
    storageBucket: 'gluten-c185f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNHaMkY0iwu70PtsvU8OH97xdd0BPEIqQ',
    appId: '1:267453690033:ios:654a5c4e10d4e147c7b290',
    messagingSenderId: '267453690033',
    projectId: 'gluten-c185f',
    storageBucket: 'gluten-c185f.appspot.com',
    iosBundleId: 'com.example.gluten',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNHaMkY0iwu70PtsvU8OH97xdd0BPEIqQ',
    appId: '1:267453690033:ios:eb1867349a164bebc7b290',
    messagingSenderId: '267453690033',
    projectId: 'gluten-c185f',
    storageBucket: 'gluten-c185f.appspot.com',
    iosBundleId: 'com.example.gluten.RunnerTests',
  );
}
